### ISSUE TITLE
Request: Update protractor depencency to the last version

### ISSUE THREAD

**Issue by rbatllet** [mllrsohn/gulp-protractor#100]
Is there any possibility to make it compatible to the protractor 3.1.x  in the near future and update the protractor dependency to this version?. 

Now, it's only compatible with 3.0.x.

**Comment by pedrro** [comment]
I made the pr #98 that do this, but was not approved yet.

**Comment by mattfritz** [comment]
Fixed in `v2.2.0`. Thank you @pedrro
