### ISSUE TITLE
e2e tests not working on fresh install

### ISSUE THREAD

**Issue by lydemeister** [mllrsohn/gulp-protractor#103]
I am using gulp, typescript, bootstrap and sass and when I run gulp test:e2e on a fresh install (and updates selenium) I get:
`UnknownError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.73 seconds
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'DESKTOP-79F9HEB', ip: '192.168.0.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_77'
Driver info: org.openqa.selenium.chrome.ChromeDriver`

**Comment by mattfritz** [comment]
This looks like Chrome failed to launch after a 60 second timeout. I don't think this is related to this plugin, but rather seems to be an issue with a Chrome installation.

I'm going to close this for now, but if you have additional information (`gulpfile`, Chrome version, replication steps) I'll reopen.

**Comment by lydemeister** [comment]
It was releated to chrome and not the plugin.
