### ISSUE TITLE
Update to protractor v4.0.0

### ISSUE THREAD

**Issue by westy92** [mllrsohn/gulp-protractor#113]
Protractor v4.0.0 was released today.
https://www.npmjs.com/package/protractor

We're currently using v3.3.0.

**Comment by mattfritz** [comment]
Released in version `2.5.0`

**Comment by zg** [comment]
Did this adhere to semver rules?

**Comment by mattfritz** [comment]
There were no public API changes and this is still compatible with Protractor v3, so there shouldn't be any compatibility issues necessitating a major bump.

**Comment by tbassetto** [comment]
@mattfritz : Actually protractor v4 has [breaking changes](https://github.com/angular/protractor/blob/master/CHANGELOG.md#breaking-changes). Some of our tests that used to run with `gulp-protractor` 2.4.x are no longer working, so you should have bumped the major version of `gulp-protractor`.

**Comment by mattfritz** [comment]
Thanks @tbassetto @zg , forgot this is still an issue https://github.com/mllrsohn/gulp-protractor/issues/101 ... My mistake. I just published `2.6.0` that reverts to Protractor `3.x.x` as well as `3.0.0` which supports Protractor `4.x.x`.  Sorry if I caused any headaches.
