### ISSUE TITLE
Is there a way to launch selenium and then run the tests from the same gulp task?

### ISSUE THREAD

**Issue by pursual** [mllrsohn/gulp-protractor#12]
I tried making the webdriver task a dependency of the test task, but gulp never realizes when the server has finished starting. Any thoughts?

**Comment by selo796** [comment]
Protractor would start a selenium-webdriver server automatically if you
omit the seleniumAddress config option ;) so all is needed is a config
file and to run protractor e2e.conf.js that's it.

**Comment by Bsunny** [comment]
@steffenmllr , as per your comment - 
"Thank for the hint. I'll publish it on npm in a minute"

Can you please let us know the module on npm? Which module should i use for this ?

if there is no module and its a commit in few files, then how to use it the code ?

**Comment by rahulmr** [comment]
@Bsunny what exactly do you want? `gulp-protractor` is the module. It depends on your gulpfile and conf file. You can refer [this](https://github.com/rahulmr/gulp-protractor-tests-on-travis-mac)
