### ISSUE TITLE
gulp-protractor autostarstop does not update chromedriver

### ISSUE THREAD

**Issue by keithdtyler** [mllrsohn/gulp-protractor#120]
It appears that gulp-protractor is trying to update webdriver every time it starts it up using the autoStartStopServer parameter, which via gulp-stream runs the webdriver_update() function, which calls the webdriver-manager binary with  args = ["update", "--standalone"].

However, it does not seem to actually update the install's copy of Chromedriver at all, which is still stuck at 2.20 even though webdriver-manager is capable of installing at least 2.22.

**Comment by fyyyyy** [comment]
I guess thats why all specs fail on travis

**Comment by keithdtyler** [comment]
The bug was in the dependency webdriver-manager https://github.com/angular/protractor/issues/3644

The sticking issue was that fixing webdriver-manager wasn't good enough until gulp-protractor was using the new version of it. It wasn't obvious that gulp-protractor downloads and uses it's own tucked-away instance of webdriver and chromedriver, so it wasn't enough to just do "npm update webdriver-manager" since that would not update the instance of chromedriver used by gulp-protractor.

(Any reason why GP installs its own copy of webdriver instead of using a more global one?)

**Comment by rahulmr** [comment]
@keithdtyler could you please confirm whether this issue is still reproducible after we updated the protractor version to ^5?

**Comment by rahulmr** [comment]
GP is now having latest version of protractor and able to update drivers as well. It also works fine with `directConnect: true`
I am closing this issue as of now
