### ISSUE TITLE
Misleading/incorrect seleniumServerJar path example in README.md

### ISSUE THREAD

**Issue by apaatsio** [mllrsohn/gulp-protractor#121]
The README says that the seleniumServerJar path is 

`./node_modules/protractor/selenium/selenium-server-standalone-2.45.0.jar`

but at least on my installation the correct path is

`./node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar`

I'm using gulp-protractor 3.0.0 and protractor 4.0.10.

**Comment by rahulmr** [comment]
Should be resolved now. Updated the information in README as well as examples are corrected now. I have fixed this for the latest one with protractor 5.1.1 and standalone driver as 3.2.0
