### ISSUE TITLE
Tests fail with error EADDRINUSE 127.0.0.1:SOME_PORT

### ISSUE THREAD

**Issue by oleksandr-strilchuk-gl** [mllrsohn/gulp-protractor#122]
I've got this message on my CI VM after changing the count of CPU cores from 2 to 4:

`[chrome #01-76]   Message:`
`[chrome #01-76]    Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:58617`
`[chrome #01-76]   Stack:`
`[chrome #01-76]     Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:58617`
`[chrome #01-76]         at ClientRequest.<anonymous> (C:\ci_bohdan\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:381:15)`
`[chrome #01-76]         at emitOne (events.js:77:13)`
`[chrome #01-76]         at ClientRequest.emit (events.js:169:7)`
`[chrome #01-76]         at Socket.socketErrorListener (_http_client.js:269:9)`
`[chrome #01-76]         at emitOne (events.js:77:13)`
`[chrome #01-76]         at Socket.emit (events.js:169:7)`
`[chrome #01-76]         at emitErrorNT (net.js:1269:8)`
`[chrome #01-76]         at nextTickCallbackWith2Args (node.js:442:9)'`
`[chrome #01-76]         at process._tickCallback (node.js:356:17)`
`[chrome #01-76]     From: Task: WebDriver.executeScript()`
`[chrome #01-76]         at Driver.schedule (C:\ci_bohdan\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:377:17)`
`[chrome #01-76]         at Driver.executeAsyncScript (C:\ci_bohdan\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:614:17)`
`[chrome #01-76]         at ProtractorBrowser.to.(anonymous function) [as executeAsyncScript] (C:\ci_bohdan\node_modules\protractor\built\browser.js:60:29)`
`[chrome #01-76]         at Object.injectMocks (C:\ci_bohdan\tests\e2e\mocks\protractor-side\mock-injector.js:11:17)`
`[chrome #01-76]         at Object.<anonymous> (C:\ci_bohdan\tests\e2e\specs\identity\users\actionsbar.spec.js:26:22)`
`[chrome #01-76]         at C:\ci_bohdan\node_modules\protractor\node_modules\jasminewd2\index.js:90:15`
`[chrome #01-76]         at new ManagedPromise (C:\ci_bohdan\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1082:7)`
`[chrome #01-76]         at controlFlowExecute (C:\ci_bohdan\node_modules\protractor\node_modules\jasminewd2\index.js:80:18)`
`[chrome #01-76]         at TaskQueue.execute_ (C:\ci_bohdan\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)`
`[chrome #01-76]         at TaskQueue.executeNext_ (C:\ci_bohdan\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)`
`[chrome #01-76]     From: Task: Run beforeEach in control flow`
`[chrome #01-76]         at Object.<anonymous> (C:\ci_bohdan\node_modules\protractor\node_modules\jasminewd2\index.js:79:14)`
`[chrome #01-76]         at C:\ci_bohdan\node_modules\protractor\node_modules\jasminewd2\index.js:103:16`
`[chrome #01-76]         at ManagedPromise.invokeCallback_ (C:\ci_bohdan\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)`
`[chrome #01-76]         at TaskQueue.execute_ (C:\ci_bohdan\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)`
`[chrome #01-76]         at TaskQueue.executeNext_ (C:\ci_bohdan\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)`
`[chrome #01-76]     From asynchronous test: `
`[chrome #01-76]     Error`
`[chrome #01-76]         at Suite.<anonymous> (C:\ci_bohdan\tests\e2e\specs\identity\users\actionsbar.spec.js:25:5)`
`[chrome #01-76]         at Object.<anonymous> (C:\ci_bohdan\tests\e2e\specs\identity\users\actionsbar.spec.js:1:1)`
`[chrome #01-76]         at Module._compile (module.js:409:26)`
`[chrome #01-76]         at Object.Module._extensions..js (module.js:416:10)`
`[chrome #01-76]         at Module.load (module.js:343:32)`
`[chrome #01-76]         at Function.Module._load (module.js:300:12)`

When run tests using code:
`var argumentList = ['--capabilities.maxInstances', 3, '--capabilities.shardTestFiles', true];`

`return gulp.src(src)`
`        .pipe(protractor({`
`            configFile: PATH/protractor_config.js,`
`            args: argumentList`
`        }))`
`        .on('error', function (e) {`
`            throw e;`
`        });`

If some tests where finished in same time and new 3 specs start running

It looks like some stuff (chromedrivers, webdrivers, selenium servers) are running parallel on same port.

Do you have any suggestions how to fix it?

**Environment:**
- OS: Windows Server 2012 R2 (x64)
- Processor: Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (4 pocessors)
- RAM: 6GB
- node js: v4.6.1
- protractor: 4.0.10
- gulp-protractor: 3.0.0

**Comment by rahulmr** [comment]
@oleksandr-strilchuk-gl do you still face this issue ? Can you check with latest version of gulp-protractor and protractor? I think using jar can be helpful but would like to check your config file or may be if you can share complete example I can help you out?

**Comment by rahulmr** [comment]
No updates. Closing issue as cleanup. Please reopen, if issue is still reproducible.
