### ISSUE TITLE
MAINTAINER NEEDED

### ISSUE THREAD

**Issue by mattfritz** [mllrsohn/gulp-protractor#125]
I no longer have time to maintain this repository and no longer work with Angular in my day-to-day, so it makes sense to hand this off to someone with a vested interest.

Please let me know if you want to take this on

cc: @steffenmllr

**Comment by rahulmr** [comment]
Let me know if I can participate and maintain

**Comment by mattfritz** [comment]
@rahulmr definitely! What is your NPM username? Let me know and I can get the process started

**Comment by hah-nan** [comment]
Yeah, glad this is so recent. I want to continue using but it doesn't work unless protractor v5 is being used. Thats all I need and then I can keep using this module

**Comment by rahulmr** [comment]
@mattfritz it is rahulmr (@rahulmr)

**Comment by mattfritz** [comment]
@rahulmr you should be good to go. Thank you for taking this on!

**Comment by steffenmllr** [comment]
Just wanted to thank @mattfritz for his work and @rahulmr to continue this project. It nice to see people wanting to contribute. We also don't use angular anymore which was the original reason I created the repo. 

@rahulmr Maybe you could ask the angular team to move the repo to the angular project. I'm happy to transfer the repo if they would do it. A lot of people are using this plugin (https://npm-stat.com/charts.html?package=gulp-protractor)

**Comment by rahulmr** [comment]
@hah-nan could you please check and report if there are any issues at your end after update to protractor ^5?

@steffenmllr thanks for your appreciation. I am bit new :) with npm and github. I will try to connect with them.  Any pointers will be helpful.
