### ISSUE TITLE
support --ignore_ssl in webdriver_update

### ISSUE THREAD

**Issue by llwt** [mllrsohn/gulp-protractor#126]
Currently there is no way to pass additional flags into the webdriver_update command. We are behind a corporate firewall and need to be able to specify the --ignore_ssl flag. The way the function is currently written makes it a bit hard to add that functionality without breaking changes, I was curious if you had any thoughts as to how to go about it? I would be more than happy to open a merge request.

**Comment by rahulmr** [comment]
There is a stupid solution or workaround if you want to try out.
Report back if it works for you. Check example.
```
var webdriver_update = require('../').webdriver_update_specific;

// Downloads the selenium webdriver
gulp.task('webdriver_update', webdriver_update({
    browsers: ['ignore_ssl']
}));
```

**Comment by rahulmr** [comment]
Let us wait for PR #127 , your issue should be fixed and you can use code like below:
```
var webdriver_update = require('../').webdriver_update_specific;

// Downloads the selenium webdriver
gulp.task('webdriver_update', webdriver_update({
    webdriverManagerArgs: ['--ignore_ssl']
}));
```
I have checked it on windows and it works perfectly.

**Comment by rahulmr** [comment]
Sorry this is now implemented. Closing this issue.

**Comment by llwt** [comment]
@rahulmr Awesome, thanks!
