### ISSUE TITLE
Not able to run webdriver_update

### ISSUE THREAD

**Issue by patrickliechty** [mllrsohn/gulp-protractor#131]
We are using protractor 5.1.1 with NodeJS 6.9.4 and gulp-protractor 4.1.0.  I run 

This is my gulpfile.js:

var webdriver_update = require("gulp-protractor").webdriver_update;

gulp.task('webdriver_update', webdriver_update);

If I run gulp webdriver_update I get this error which looks like it is expecting an older version of npm which does not flatten the dependencies.

[10:45:37] I/file_manager - creating folder /Users/liechtypo/sandbox/indexing3/node_modules/protractor/node_modules/webdriver-manager/selenium

**Comment by rahulmr** [comment]
not sure but seems like access issue. It is not able to create folder or access folder  `selenium`  and/or its contents.
I had a similar issue on my MacBook and Ubuntu VM. try to give access and check once again. `chmod -Rf 777 selenium`

**Comment by patrickliechty** [comment]
But it should not be trying to create the folder.  This is npm version 3 that flattens the dependencies.  No longer do we have node_modules folders under a dependency.

**Comment by rahulmr** [comment]
Yes, you are right, but `gulp-protractor` is not doing here anything. It is `protractor` under which the folder is there. May be should first try `./node_modules/.bin/webdriver-manager update` and check whether those folders are created or not.  And check permissions for selenium folder. I see there is some problem with `gulp-protractor` when access is restricted in Linux or Mac. That I will have to debug.

**Comment by rahulmr** [comment]
@patrickliechty could you please refer link [here][1]
It is working fine at my end on travis ci.
Let me know if I can close this issue.

[1]: https://travis-ci.org/rahulmr/gulp-protractor-tests-on-travis-mac/jobs/213531517
