### ISSUE TITLE
How do I run webdriver standalone task ahead of protractor task via gulp

### ISSUE THREAD

**Issue by kungfuPanda123** [mllrsohn/gulp-protractor#134]
Hi,
I'm trying to run protractor automatically using gulp-protractor plugin. This whole process works fine when using protractor commands and explicitly running the web drivers individually.
The same works when running using gulp-protractor, provided ie webdriver is started manually in background before triggering the gulp task.

**How do I run webdriver standalone task ahead of protractor task via gulp??**

Below is the code snippet of my `Gulp task`

`var protractor = require("gulp-protractor").protractor;
var webdriverupdate = require("gulp-protractor").webdriver_update;;
var webdriver_standalone = require("gulp-protractor").webdriver_standalone;

// This task is to update  & run the webdriver
gulp.task('webdriver_standalone', webdriver_standalone);
gulp.task('webdriverUpdate', ['webdriver_standalone'], function () {
  browsers: ['chrome', 'ie']
});

//for running protractor E2E test cases
gulp.task('protractor', function (callback) {
gulp
    .src(['./e2e/sanity/shared/*.spec.ts',
            './e2e/sanity/app-header/*.spec.ts',
            ])
    .pipe(protractor({
        'configFile': 'Protractor.conf.js',
    }))
    .on('error', function (e) {
        console.log(e);
    })
    .on('end', callback);
  });

gulp.task('default',['webdriverUpdate','protractor']);`

Below is the code snippet of my `protractor.config.js`

`const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
allScriptsTimeout: 1100,
suites: {
    shared: ['./e2e/sanity/shared/*.ts'] ,
    appheader: ['./e2e/sanity/app-header/*.spec.ts']
},
    multiCapabilities: 
    [{
          seleniumAddress: 'http://localhost:5555/',
          'browserName': 'internet explorer',            
          'platform': 'windows 10',
          'version': '11',
          'ignoreProtectedModeSettings': true,
    },
    { 
         seleniumAddress: 'http://localhost:4444/wd/hub',
        'browserName': 'chrome',
        'ignoreProtectedModeSettings': true,
}],
};`

Output: 

`D:\xxx\xx\xx\xx\xx\xx>gulp protractor
[15:40:41] Using gulpfile D:\xxx\xx\xx\xx\xx\xx\gulpfile.js
[15:40:41] Starting 'webdriverUpdate'...
[15:40:41] Finished 'webdriverUpdate' after 59 μs
[15:40:41] Starting 'protractor'...
(node:14172) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[15:40:43] I/launcher - Running 2 instances of WebDriver
[15:40:45] I/testLogger 
[15:40:45] I/testLogger - [internet explorer 11 windows 10 #01] PID: 25876
[internet explorer 11 windows 10 #01] (node:25876) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[internet explorer 11 windows 10 #01] [15:40:44] I/hosted - Using the selenium server at http://localhost:5555/
[internet explorer 11 windows 10 #01]
[internet explorer 11 windows 10 #01] D:\xxx\xx\xx\xx\xx\xx\node_modules\selenium-webdriver\http\index.js:238
[internet explorer 11 windows 10 #01]       onError(new Error(message));
[internet explorer 11 windows 10 #01]               ^
[internet explorer 11 windows 10 #01] Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:5555
[internet explorer 11 windows 10 #01]     at ClientRequest.<anonymous> (D:\xxx\xx\xx\xx\xx\xx\node_modules\selenium-webdriver\http\index.js:238:15)
[internet explorer 11 windows 10 #01]     at emitOne (events.js:116:13)
[internet explorer 11 windows 10 #01]     at ClientRequest.emit (events.js:211:7)
[internet explorer 11 windows 10 #01]     at Socket.socketErrorListener (_http_client.js:387:9)
[internet explorer 11 windows 10 #01]     at emitOne (events.js:116:13)
[internet explorer 11 windows 10 #01]     at Socket.emit (events.js:211:7)
[internet explorer 11 windows 10 #01]     at emitErrorNT (internal/streams/destroy.js:64:8)
[internet explorer 11 windows 10 #01]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[internet explorer 11 windows 10 #01]     at process._tickCallback (internal/process/next_tick.js:180:9)
[internet explorer 11 windows 10 #01] From: Task: WebDriver.createSession()
[internet explorer 11 windows 10 #01]     at Function.createSession (D:\xxx\xx\xx\xx\xx\xx\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
[internet explorer 11 windows 10 #01]     at createDriver (D:\xxx\xx\xx\xx\xx\xx\node_modules\selenium-webdriver\index.js:170:33)
[internet explorer 11 windows 10 #01]     at Builder.build (D:\xxx\xx\xx\xx\xx\xx\node_modules\selenium-webdriver\index.js:635:14)
[internet explorer 11 windows 10 #01]     at Hosted.getNewDriver (D:\xxx\xx\xx\xx\xx\xx\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
[internet explorer 11 windows 10 #01]     at Runner.createBrowser (D:\xxx\xx\xx\xx\xx\xx\node_modules\protractor\built\runner.js:195:43)
[internet explorer 11 windows 10 #01]     at q.then.then (D:\xxx\xx\xx\xx\xx\xx\node_modules\protractor\built\runner.js:339:29)
[internet explorer 11 windows 10 #01]     at _fulfilled (D:\xxx\xx\xx\xx\xx\xx\node_modules\q\q.js:834:54)
[internet explorer 11 windows 10 #01]     at self.promiseDispatch.done (D:\xxx\xx\xx\xx\xx\xx\node_modules\q\q.js:863:30)
[internet explorer 11 windows 10 #01]     at Promise.promise.promiseDispatch (D:\MyWorkspace\Dev\Sandbox\VueFrameworkDev\VueFramework2.0\VueFramework2.0\node_modules\q\q.js:796:13)
[internet explorer 11 windows 10 #01]     at D:\MyWorkspace\Dev\Sandbox\VueFrameworkDev\VueFramework2.0\VueFramework2.0\node_modules\q\q.js:556:49

[15:40:45] I/testLogger -

[15:40:45] E/launcher - Runner process exited unexpectedly with error code: 1
[15:40:45] I/launcher - 1 instance(s) of WebDriver still running```

**Comment by rahulmr** [comment]
@kungfuPanda123 Hope you know how this plugin works? Please check the example and example_2. Your question is also not clear. Please provide details of your environment.
If you want to run tests there is no need to use standalone server in case of chromedriver. I think the same applies for other drivers with the `directConnect: true` option. Please read more about selenium webdriver architecture and options provided by protractor

**Comment by rahulmr** [comment]
check [this](https://github.com/mllrsohn/gulp-protractor/blob/master/example/Gulpfile.js) example.
This issue is not related to `gulp-protractor` as such so closing it. You can still continue your queries.
