### ISSUE TITLE
Replace deprecated dependency gulp-util

### ISSUE THREAD

**Issue by TheDancingCode** [mllrsohn/gulp-protractor#135]
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is popular but still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

**Comment by karstens** [comment]
Is there an estimate of when this is going to be released ?

**Comment by dmikrot** [comment]
@SachaMPS @steffenmllr This has been merged in, but it has not been published to npm, so it cannot be installed and used. Please publish a new release of gulp-protractor to npm, so that we can remove gulp-utils as a dependency when using gulp 4.

**Comment by patelhitul** [comment]
When should we expect it to be released?
