### ISSUE TITLE
webdriver_update tasks does not work if protractor installed on higher level

### ISSUE THREAD

**Issue by rogierschouten** [mllrsohn/gulp-protractor#26]
My devDependencies were accumulating, totalling 20.000+ files, so I moved them a directory up, in order to share them between different (non-published) NPM modules. 
Node is fine with that, as it searches recursively up to find modules. However, webdriver_update expects that Gulp is run in the directory that also contains ./node_modules/.bin/webdriver_manager.cmd. 

Next to my rather corner-casey use case, the gulp file might in any case not be executed with the module directory as cwd. Therefore maybe it is handy to replace the hard-coded directory with an actual search for the module?

**Comment by mattfritz** [comment]
Is this still an issue? I'm closing for now, but let me know and I'll take a look.
