### ISSUE TITLE
 Unhandled 'error' event spawn ENOENT

### ISSUE THREAD

**Issue by Apercu** [mllrsohn/gulp-protractor#32]
Running the `gulp e2etests:run` after updating the webdriver and the new references in the config file, I got the following error, both in my project and the `exemple_2` of this repo : 

    Starting selenium standalone server...   

    events.js:72
        throw er; // Unhandled 'error' event
              ^ 
    Error: spawn ENOENT
        at errnoException (child_process.js:988:11)
        at Process.ChildProcess._handle.onexit (child_process.js:779:34)
    { plugin: 'gulp-protractor', 
        showStack: false,
        message: 'protractor exited with code 8' }

Running tests give me 5 passing and 1 pending.

I'm under Archlinux, but maybe linked with #13 ?

Thanks !

**Comment by AustinFelipe** [comment]
+1 :+1:
