### ISSUE TITLE
Add support for debug mode

### ISSUE THREAD

**Issue by mpetrovich** [mllrsohn/gulp-protractor#34]
Protractor allows tests to be paused with `browser.debugger()` when run in [debug mode](https://github.com/angular/protractor/blob/master/docs/debugging.md#pausing-to-debug) like so:
```
protractor debug debugging/failureConf.js
```
However, gulp-protractor does not appear to support this feature. It would be nice to be able to enable it via the options object:
```
protractor({
    debug: true,
    configFile: 'tests/protractor/protractor.conf.js'
})
```

**Comment by mattfritz** [comment]
This was added in `v1.0.0`
