### ISSUE TITLE
Selenium server does not shut down

### ISSUE THREAD

**Issue by resistdesign** [mllrsohn/gulp-protractor#41]
When allowing the `protractor` function to run the selenium server itself it says it's shutting down the selenium server but just hangs.

**Comment by dellheng** [comment]
thank you mruzekw
use this
gulp.task('server:e2e', function() {
  connect.server({
    root: 'www'
  });
});
donot use
gulp.task('server:livereload', ['livereload'], function() {
  connect.server({
    root: 'www',
    livereload: true
  });
});
