### ISSUE TITLE
args not working

### ISSUE THREAD

**Issue by raDiesle** [mllrsohn/gulp-protractor#42]
on windows 7: defining 

protractor({
 configFile : "..."
args : {
}

it fails ongul-protractor:43     args.push("--specs")  

object<#>   has no method push

several combinations does not work.
I expect options : {} is incorrect

**Comment by brettmcginnis** [comment]
The command below returns the following error.

------Gulp Command------
return gulp.src(tests)
            .pipe(protractor({
                args: ['--specs', '**/*.scenarios.js'],
                configFile: configFile
            }))
            .on('error', logErrorAndContinue)
            .once('end', function() {
                process.exit();
            });

------Gulp task error------
/Users/username/garuda/node_modules/protractor/lib/cli.js:111
  var patterns = list.split(',');
                      ^
TypeError: Object **/*.scenarios.js,/Users/username/garuda/test/e2e/index.page.js,/Users/username/garuda/test/e2e/protractor.conf.js,/Users/username/garuda/test/e2e/auth/auth.scenarios.js,/Users/username/garuda/test/e2e/focus/focus.scenarios.js,/Users/username/garuda/test/e2e/menu/menu.modal.js,/Users/username/garuda/test/e2e/menu/menu.scenarios.js,/Users/username/garuda/test/e2e/settings/settings.account.page.js,/Users/username/garuda/test/e2e/ping/endpoints.scenarios.js,/Users/username/garuda/test/e2e/signin/signin.modal.js,/Users/username/garuda/test/e2e/signin/signin.page.js,/Users/username/garuda/test/e2e/signin/signin.scenarios.js,/Users/username/garuda/test/e2e/util/beforeAll.js,/Users/username/garuda/test/e2e/util/fixture.js,/Users/username/garuda/test/e2e/util/helper.js,/Users/username/garuda/test/e2e/util/matchers.js,/Users/username/garuda/test/e2e/signout/signout.modal.js has no method 'split'
    at processFilePatterns_ (/Users/username/garuda/node_modules/protractor/lib/cli.js:111:23)
    at Object.<anonymous> (/Users/username/garuda/node_modules/protractor/lib/cli.js:119:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/username/garuda/node_modules/protractor/bin/protractor:5:1)
    at Module._compile (module.js:456:26)
Error: protractor

**Comment by afeinber** [comment]
Getting the same error as brettmcginnis.

**Comment by pccjamie** [comment]
+1

**Comment by jhuiting** [comment]
Same problem here, any updates on this?

**Comment by eolognt** [comment]
Get `var patterns = list.split(',');` as well and don't know any good alternative.

**Comment by mattfritz** [comment]
Agreed, all specs should be piped into the protractor plugin via `gulp.src`.

**Comment by brettmcginnis** [comment]
Is there a commit associated with this fix? If I am understanding correctly all specs should be included in the src and spec args flag specifies which sub set that should be run.

**Comment by mattfritz** [comment]
@brettmcginnis that should be the case, the `--spec` flag should override and focus a spec file.

I closed this because I assumed (maybe prematurely) that this was improper use. @eolognt had success passing the `--spec` flag to `args` with a single file.

According to `protractor` [cli docs](https://github.com/angular/protractor/blob/master/lib/cli.js#L46) this flag takes a comma-separated set of files and not a glob. `protractor` does not support glob matching in their [cli parser](https://github.com/angular/protractor/blob/master/lib/cli.js#L110).
