### ISSUE TITLE
Error with gulp-protractor on xvfb centos6

### ISSUE THREAD

**Issue by cedriclombardot** [mllrsohn/gulp-protractor#49]
Hi ,

I got the next error look like #10

```
events.js:72
throw er; // Unhandled 'error' event
^
Error: spawn ENOENT
at errnoException (child_process.js:1101:11)
at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

But with last version of gulp-protractor on a centos-6 server with xvfb

node : v0.10.35
npm : 2.1.18
java: jdk 1.7.0_09

Can you help me to debug ?

**Comment by sdoran** [comment]
I'm seeing the same issue. The tests run fine separately just not in gulp-protractor.

node: v0.10.22
npm: 1.4.28
java: jdk 1.7.0_71

**Comment by mattfritz** [comment]
Is this still an issue? If you have the webdriver version, that would help as well.

**Comment by rahulmr** [comment]
We will no longer support node < 6.x and npm < 3 . If it works great else upgrade your node and npm version.
`gulp-protractor` works fine with `xvfb`  check build [here][1]. Though I am still working to make it perfect.

[1]: https://travis-ci.org/rahulmr/gulp-protractor-tests-on-travis-mac/builds/211290517
