### ISSUE TITLE
Is there any way to know if protractor failed because of webdriver fail?

### ISSUE THREAD

**Issue by sochka** [mllrsohn/gulp-protractor#52]
I'd like to detect if protractor fails because webdriver wasn't able to start. Is there any way to do that?

Thanks.

**Comment by RobbinHabermehl** [comment]
If that's the case, that will be stated pretty clearly in the console. What's the error?

**Comment by sochka** [comment]
I have to do that programmatically. The error happens with webdriver startup connection problems (I can't find the error now, it happens only on Travis CI (sometimes) and I'd like to intercept that during my build phase such that I'd allow to skip tests at all).

**Comment by mattfritz** [comment]
Most of the time, Travis needs time to set up `xvfb` and selenium before starting the tests (https://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server) if you are getting connection errors. I'm going to close this for now, but we can discuss further if needed
