### ISSUE TITLE
Issues on OSX!

### ISSUE THREAD

**Issue by bcherny** [mllrsohn/gulp-protractor#56]
I wanted to document how I got this to work on OSX, in case anyone needs help in the future. I'm using Protractor v1.7.0 and gulp-protractor v0.0.12. @mllrsohn feel free to move this somewhere else.

I started by installing gulp-protractor, and using it with the following task:

```js
gulp.task ('e2e', function(){
  gulp
    .src(SRCDIR + '/**/*.e2e.js')
    .pipe(protractor({
      configFile: 'protractor.conf.coffee'
    })
})
```

When I ran `gulp e2e`, I got the following error:

```text
[chrome #1a] Could not find chromedriver at /Users/bcherny/Sites/webapp/node_modules/protractor/selenium/chromedriver.exe
```

Googling wasn't very helpful, but installing selenium was:

```sh
npm i selenium-standalone-jar --save-dev
```

I then added Selenium to my protractor.conf.coffee, per your docs:

```coffee
seleniumServerJar: './node_modules/selenium-standalone-jar/bin/selenium-server-standalone-2.44.0.jar'
```

Running `gulp e2e` again, I got the following error:

```text
[chrome #1a] /Users/bcherny/Sites/webapp/node_modules/protractor/lib/driverProviders/local.js:54
[chrome #1a]         throw new Error('Could not find chromedriver at ' +
[chrome #1a]               ^
[chrome #1a] Error: Could not find chromedriver at /Users/bcherny/Sites/webapp/node_modules/protractor/selenium/chromedriver
```

The solution was to install the missing dependency:

```sh
npm i chromedriver --save-dev
```

And add it to my protractor.conf.coffee, as per the [protractor docs](https://github.com/angular/protractor/blob/1.7.0/docs/referenceConf.js#L41):

```coffee
chromeDriver: './node_modules/chromedriver/bin/chromedriver'
```

Finally, `gulp e2e` ran my tests successfully.

Hopefully this helps someone!

**Comment by Stephn-R** [comment]
Thank you for this!

**Comment by wcandillon** [comment]
@bcherny Thank you. :+1:

**Comment by cypherq** [comment]
@bcherny Thank you!

**Comment by mattfritz** [comment]
I think this is valuable to archive as an alternative solution, but using the `webdriver_update` and the `webdriver_standalone` is the supported option.

```js
var protractor = require("gulp-protractor").protractor;
var webdriver_update = require("gulp-protractor").webdriver_update;

gulp.task('webdriver_update', webdriver_update);

gulp.task ('e2e', ['webdriver_update'], function(){
  gulp
    .src(SRCDIR + '/**/*.e2e.js')
    .pipe(protractor({
      configFile: 'protractor.conf.coffee'
    })
})
```

This guarantees that the webdriver/chromedriver binaries are properly downloaded into the expected `node_modules/protractor/selenium/` directory
