### ISSUE TITLE
Possible to pipe into protractor?

### ISSUE THREAD

**Issue by bcherny** [mllrsohn/gulp-protractor#57]
I am browserifying my test files, and would like to pipe them into protractor instead of having to write to a temporary file, which is un-gulplike and un-nodelike. I tried piping the browserify output stream into protractor, but I keep getting errors:

```text
1) Exception loading: /Users/bcherny/Sites/webapp Error
   Message:
     Error: Cannot find module '/Users/bcherny/Sites/webapp'
   Stacktrace:
     Error: Cannot find module '/Users/bcherny/Sites/webapp'
    at require (module.js:380:17)
    at Function.promise (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:650:9)
    at _fulfilled (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:759:13)
    at /Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:525:49
    at flush (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
...
```

Here's the relevant excerpt from my gulpfile:

```coffee
gulp.task 'e2e', ->

  browserify
    entries: [
      'e2e/tests/one.js'
      'e2e/tests/two.js'
    ]
  .bundle()
  .on 'error', (_.partialRight error, 'Browserify')
  .pipe protractor
    configFile: 'protractor.conf.coffee'
  .on 'error', (_.partialRight error, 'Protractor')
```

When I use temporary files, everything works fine:

```coffee
gulp.task 'e2e', ['browserify-e2e'], ->

  gulp
    .src [
      "tmp/**/*.js"
    ]
    .pipe protractor
      configFile: 'protractor.conf.coffee'
    .on 'error', (_.partialRight error, 'Protractor')

gulp.task 'browserify-e2e', ->

  browserify
    entries: [
      'e2e/tests/one.js'
      'e2e/tests/two.js'
    ]
  .bundle()
  .on 'error', (_.partialRight error, 'Browserify')
  .pipe source 'test.js'
  .pipe do buffer
  .pipe gulp.dest "tmp/"
```

x/post https://github.com/angular/protractor/issues/1858

**Comment by j0hnsmith** [comment]
Why do you need to browserify your e2e spec files, you can already use `require` in them. This plugin allows you to pipe them to protractor, eg

    gulp.task('test:e2e', [], function() {
        gulp.src(['e2e/test1.spec.js', 'e2e/test2.spec.js'])
            .pipe(protractor({
                configFile: "protractor.conf.js",
                args: [
                    '--baseUrl', 'http://somewhere-your-app-is-running'
                ]
            }))
            .on('error', function(e) {
                throw e;
            });
    });

And example test

    var _ = require('lodash');
    console.log('_', _);

    describe('Your login page', function() {
        it("should have a title of 'Login'", function() {
            browser.get('/login/');
            browser.driver.wait(function() {
                return browser.driver.getCurrentUrl().then(function(url) {
                    return /\/login\//.test(url);
                });
            });

            expect(browser.getTitle()).toEqual('Login');
        });

**Comment by mattfritz** [comment]
This plugin runs protractor with CLI options pointed at spec files on disk. It's not an issue with the plugin, but a limitation of invoking protractor.
