### ISSUE TITLE
How to keep running the Webdriver instance when a test fail?

### ISSUE THREAD

**Issue by earlyriser** [mllrsohn/gulp-protractor#58]
I've searched for hours and I wonder if this is possible.

I start a "gulp serve" and when I modify my .js or html files I can see the tests being executed every time I save. However when the test is failed, I got this:

1 test, 1 assertion, 1 failure
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
{ [Error: protractor exited with code 1]
  message: 'protractor exited with code 1',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function] } }

And I need to CTRL-C my console window and do a "gulp serve" again if I want to continue with the tests being executed. Is there a way to avoid this?

**Comment by humphreyn** [comment]
Hi earlyriser,

Did you get anywhere with this as I am having a similar problem?

**Comment by earlyriser** [comment]
I don't remember if I found a solution for that. Sorry. At this point I'm just using Protractor without Gulp.

**Comment by humphreyn** [comment]
I'm now using Gulp-Plumber to get around exit code 1 to catch and then emit to gulp pipelin create cucumber reports

**Comment by mattfritz** [comment]
You can start a standalone webdriver instance via `gulp webdriver_standalone`, without passing a selenium server jar config option to protractor. Then when you run a `watch` or `serve` etc. the standalone instance will not be terminated.

```js
var webdriver_standalone = require("gulp-protractor").webdriver_standalone;
gulp.task('webdriver_standalone', webdriver_standalone);
```

As far as the task hanging at the end, I would have to see your gulpfile to see what's going on there. Sounds like this isn't an issue anymore, so I'm going to close it. Feel free to submit more information and I'll take a look.
