### ISSUE TITLE
Upgrade to Protractor 2.0

### ISSUE THREAD

**Issue by bradyisom** [mllrsohn/gulp-protractor#61]
Because of angular/protractor#1872 and angular/protractor#1734, Protractor 1.x does not work with Firefox. Please update the protractor dependency to 2.0 for gulp-protractor, so we can take advantage of these fixes.

**Comment by steffenmllr** [comment]
2.0 is supported in https://github.com/mllrsohn/gulp-protractor/pull/60

**Comment by bradyisom** [comment]
Thank you!
