### ISSUE TITLE
Corrupt jarfile selenium-server-standalone-2.45.0.jar

### ISSUE THREAD

**Issue by Salasar** [mllrsohn/gulp-protractor#63]
node v0.12.1
selenium-server-standalone-2.45.0.jar

My tasks in gulp: 

var webdriverUpdate = require('gulp-protractor').webdriver_update;
var webdriverStandalone = require('gulp-protractor').webdriver_standalone;

gulp.task('webdriver-update', webdriverUpdate);
gulp.task('webdriver-standalone', webdriverStandalone);

Task started in gulp via Webstorm.

I was update selenium server driver by "webdriver-update" gulptask and try start "webdriver-standalone" task, but get error "Invalid or corrupt jarfile selenium-server-standalone-2.45.0.jar".

I was download selenium jar manually from http://docs.seleniumhq.org/download/ and replace file in webdriver-manager/selenium folder and "webdriver-standalone" task work correct! Selenium server was started.

Please, check source of files for download.

**Comment by bluesliverx** [comment]
I ran into this same issue, gulp-protractor 1.0.0

**Comment by mattfritz** [comment]
The source of the webdriver binaries is managed by the [angular/protractor](https://github.com/angular/protractor/) team [here](https://github.com/angular/protractor/blob/master/bin/webdriver-manager). Corrupt binaries can also be an issue with proxy settings etc.

I'm going to close this for now, let me know if you see similar issues in the future.

**Comment by bluesliverx** [comment]
Forgot I commented on this. My issue is that the download only partially completed on first run before I cancelled it, etc.  Deleting the corrupt files allowed them to redownload and it was fine.
