### ISSUE TITLE
disabled tests/suites are NOT skipped

### ISSUE THREAD

**Issue by pccjamie** [mllrsohn/gulp-protractor#66]
When I run my entire set of spec files using 'protractor' command, everything runs as expected. Specifically, suites that I have disabled like so:
<code>
xdescribe('my suite',function(){
//run a suite
};

xit('my test', function(){
//run a test
}
</code>
..are skipped, as expected.
HOwever, when I try to run the same thing using gulp-protractor, the runner goes through my entire spec directory and then marks what should be skipped tests as failed tests.  Any ideas?

**Comment by pccjamie** [comment]
This is the file that handles running gulp protractor:
<pre>
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var browserSync = require('browser-sync');
var paths = gulp.paths;

// Downloads the selenium webdriver
gulp.task('webdriver-update', $.protractor.webdriver_update);
gulp.task('webdriver-standalone', $.protractor.webdriver_standalone);

function runProtractor(done) {
  gulp.src(paths.e2e + '/**/*.js')
    .pipe($.protractor.protractor({
      configFile: 'protractor.conf.js'
    }))
    .on('error', function (err) {
      // Make sure failed tests cause gulp to exit non-zero
      throw err;
    })
    .on('end', function () {
      // Close browser sync server
      browserSync.exit();
      done();
    });
}

gulp.task('protractor', ['protractor:src']);
gulp.task('protractor:src', ['serve:e2e', 'webdriver-update'], runProtractor);
gulp.task('protractor:dist', ['serve:e2e-dist', 'webdriver-update'], runProtractor);
</pre>

**Comment by mpiasta-ca** [comment]
Same issue. 

1. When I `xdescribe(...)` a test file, it is skipped, but gulp-protractor renders it as an error response (trigger `on.('error', ...)`).

2. The browser window remains open when all the tests finish, where usually all the browser windows would have been closed.

**Comment by mattfritz** [comment]
I cannot replicate this... Both `xdescribe` and `xit` work for me using the plugin with Jasmine.

I'm going to close this for now. Let me know if you have more info down the line.
