### ISSUE TITLE
'Quiter' logging?

### ISSUE THREAD

**Issue by bjones6** [mllrsohn/gulp-protractor#68]
Hey there, just came to ask if theirs an easy way to limit the logging in the console, it's a little verbose for my tastes and most of it has nothing to do with my tests!

Thanks for the great plug-in,

Ben

**Comment by mattfritz** [comment]
I'm not sure which output you'd like suppressed, but if you give an example I can probably take a look.

Closing this for now since the issue is so old. Let me know and I'll reopen if necessary
