### ISSUE TITLE
Pass proxy

### ISSUE THREAD

**Issue by nhanh2301** [mllrsohn/gulp-protractor#69]
Please see my code below:

'use strict';

var gulp = require('gulp'),
    shell = require('gulp-shell'),
    protractor = require('gulp-protractor').protractor,
    webdriver_update = require('gulp-protractor').webdriver_update;

function runMochaOnWebdriver() {
    shell.task('webdriver-manager start &', {quiet: true})();

```
//Allow webdriver to start, should not take more than 4181ms
setTimeout(function() {
    return shell.task('_iosTest=0 mocha ./**/*.test.js')();
}, 4181);
```

}

function runMochaOnAppium() {
    shell.task('appium', {quiet: true})();

```
//Allow webdriver to start, should not take more than 4181ms
setTimeout(function() {
    return shell.task('_iosTest=1 mocha ./**/*.test.js')();
}, 4181);
```

}

gulp.task('test-e2e', ['webdriver-update'], runMochaOnWebdriver);
gulp.task('test-ios', runMochaOnAppium);
gulp.task('webdriver-update', webdriver_update);

---

When run script, i can't update webdriver because my computer behind proxy. how to config args for pass proxy?

Logs error:

Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.15/chromedriver_mac32.zip...
Error: Got error Error: getaddrinfo ENOTFOUND from https://chromedriver.storage.googleapis.com/2.15/chromedriver_mac32.zip
Error: Got error Error: getaddrinfo ENOTFOUND from https://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar

**Comment by maxime-menard** [comment]
+1

**Comment by balasenthil-d** [comment]
I am facing the same issue as well

**Comment by skc382** [comment]
+1

**Comment by skc382** [comment]
My tests are behind a company firewall. I set the npm proxy as npm config set proxy http://URL...
and also I set the http proxy as set http_proxy=http://URL'. No Luck. Same Time out error as above.

**Comment by NightFox7** [comment]
+1

**Comment by khadirbaaoua** [comment]
+1

**Comment by maximesenecal** [comment]
+1

**Comment by rahulmr** [comment]
Is this really required?
Can you people try the [this link][1] and confirm whether it works or not.


[1]: http://www.jomendez.com/2015/02/03/installing-protractor-npm-windows-environment-behind-proxy/

**Comment by JanAschenbrenner** [comment]
I use gulp to start my e2e test and define the proxy settings there:
`const webdriver_update = require('gulp-protractor').webdriver_update_specific;

gulp.task('webdriver_update', [], webdriver_update({  
    webdriverManagerArgs: [  
        '--proxy http://proxyserver.mycompony.de:1234',  
        '--ignore_ssl'  
    ]
}))`

**Comment by rahulmr** [comment]
As mentioned by @JanAschenbrenner the option should be `'--proxy=http://proxyserver.mycompany.de:1234'`
So closing this one as well.
