### ISSUE TITLE
params cannot be passed through args

### ISSUE THREAD

**Issue by debrice** [mllrsohn/gulp-protractor#71]
When trying to pass custom params throught protractor `--params`, the argument is being sliced per letters and stored as an array. Any idea why ?

``` coffee
gulp.task 'protractor', ['combine_minifiy'], ->
  gulp.src 'test/**/*.spec.coffee'
  .pipe protractor
      configFile: 'test/protractor.conf.coffee'
      args: ['--params', 'email=x@x.com']
      # same behavior when passing args: ['--params', ['email=x@x.com']]
  .on 'error', (err) ->
    console.log "protractor failed: #{err.message}"
```

Running the test with a `console.log browser.params` outputs the following

``` js
{ '0': 'e',
  '1': 'm',
  '2': 'a',
  '3': 'i',
  '4': 'l',
  '5': '=',
  '6': 'x',
  '7': '@',
  '8': 'x',
  '9': '.',
  '10': 'c',
  '11': 'o',
  '12': 'm',
  email: 'user@domain.com',
  password: '******'}
```

**Comment by karneaud** [comment]
+1

**Comment by JT-Bruch** [comment]
Did this get resolved?

I see a number of related issues via #3 #16 and #40 but there does not seem to be a good way of handling this.  (or at least I've missed it in the docs)

**Comment by sonhu** [comment]
Hi Debrice,

It took me quite some time to figure out how to pass params (definitely not well documented) but it is possible currently using the format in the below code snippet.

```javascript
args: [
    '--suite','yourspec',    
   '--params.environment','development',    
   '--params.email','x@x.com'
]
```

**Comment by rahulmr** [comment]
README is now updated
