### ISSUE TITLE
Change dependency release strategy

### ISSUE THREAD

**Issue by MarcLoupias** [mllrsohn/gulp-protractor#82]
The current package.json for dependencies : 
```
"dependencies": {
    "event-stream": "^3.1.4",
    "async": ">=0.7.0 <1.0.0",
    "dargs": ">=0.1.0 <4.0.0",
    "gulp-util": ">=2.2.14 <4.0.0",
    "protractor": "^2.0.0"
  }
```

You should change this to 
```
"dependencies": {
    "event-stream": "~3.1.4",
    "async": ">=0.7.0 <1.0.0",
    "dargs": ">=0.1.0 <4.0.0",
    "gulp-util": ">=2.2.14 <4.0.0",
    "protractor": "~2.0.0"
  }
```
By using caret ( ^ ) you enable minor updates without any actions on your own package.
It means that gulp-protractor user can upgrade a major dependency like protractor without any notice.
Minor update add features to a package, theses features can introduce breaking changes.

Using tildes ( ~ ) is a lot more secure and safe, only patch updates are available.

I ran into this case with [this protractor issue](https://github.com/angular/protractor/issues/2551) on windows. 

My gulp-protractor was installed since 1 month (so protractor v2.1) then a bunch of new developpers joined the project they installed their dev tools (so gulp-protractor with protractor v2.3 without any changes in gulp-protractor version number) and their e2e tests failed. It takes me some hours to undestand the problem.

**Comment by rothlis** [comment]
+1

**Comment by iamryandrake** [comment]
+1

**Comment by iamryandrake** [comment]
Also, this is using a version of Protractor that's currently breaking. 

See:
- https://github.com/angular/protractor/issues/1760
- https://github.com/Dineshs91/devlog/commit/053c680ae7ca47b521daa24b3ddeaee52d9d59c3

**Comment by mattfritz** [comment]
Fixed with https://github.com/mllrsohn/gulp-protractor/commit/3aaa40ea1cfadac3fd74763fcf21732b5dc54a58

Thanks!
