### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by mo3taz-abdallh** [mllrsohn/gulp-protractor#83]
Hello 
Evey time i run gulp-protractor i got the following issue
read ECONNRESET from https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
Error: Got error Error: read ECONNRESET from https://chromedriver.storage.googleapis.com/2.19/chromedriver_mac32.zip

**Comment by atwright147** [comment]
Me too

**Comment by mattfritz** [comment]
I think this is an issue with either a proxy or possible downtime/inconsistency with googleapis.com during that time period. The error happens when the server is reachable but not responding. Closing for now, let me know if you see this again.

**Comment by ArchmageInc** [comment]
This could also be an issue with the protractor / selenium configuration files, not gulp-protractor.
