### ISSUE TITLE
Protractor 3.0.0+ support.

### ISSUE THREAD

**Issue by brocsk** [mllrsohn/gulp-protractor#84]
Protractor 3.0.0 is out and I tried upgrading today. When attempting to shrinkwrap protractor@3.0.0 with gulp-protractor@1.0.0 I got an error. 

"gulp-protractor requires protractor@'^2.0.0' but will load .... which is version 3.0.0"

I fixed it locally by bumping the dependency to ^3.0.0.

**Comment by mattfritz** [comment]
Fixed with https://github.com/mllrsohn/gulp-protractor/commit/3aaa40ea1cfadac3fd74763fcf21732b5dc54a58
