### ISSUE TITLE
MAINTAINER NEEDED

### ISSUE THREAD

**Issue by steffenmllr** [mllrsohn/gulp-protractor#87]
As you might see I don't have to time to look at PRs and keep the dependencies up to date - if you want to maintain this module (cleaning up Issues, PRs, keeping the dependencies up to date, ..) comment here and I give you access rights to the repo and publishing rights to npm

**Comment by mattfritz** [comment]
@steffenmllr I just forked this today, but I would be glad to maintain this repo if you need the help. Let me know, thanks!

**Comment by steffenmllr** [comment]
Added you to the repo and to npm - thanks for your help!

**Comment by mattfritz** [comment]
Great, thank you!

**Comment by manoj9788** [comment]
I can help @mattfritz  if an extra hand is required. Thanks
