### ISSUE TITLE
Protractor 3.0 webdrive-manager not found

### ISSUE THREAD

**Issue by DatenMetzgerX** [mllrsohn/gulp-protractor#88]
Gulp-protractor cannot find the webdrive-manager.cmd when using protractor 3.0. 

```
11:11:10] Using gulpfile d:\jenkins-1.616\jobs\upgrade-protractor\workspace\gulpfile.js
[11:11:10] Starting 'e2e'...
[11:11:10] Starting 'webdriver_update'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn d:\jenkins-1.616\jobs\upgrade-protractor\workspace\node_modules\protractor\bin\webdriver-manager.cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sambernet** [comment]
The .cmd file is actually available, but to be found in 
node_modules\.bin

This seems to be a regression in 2.0.0, works again after downgrading.
This is on Node v5.1.0 / npm 3.5.0

**Comment by mattfritz** [comment]
I can take a look at this later on today, but I don't have a Windows machine on hand. @sambernet do you have a stack trace? Does running `webdriver-manager.cmd` manually work as expected?

In the past, this error seems to be related to Windows permissions or the Java executable. Are you running your command prompt as an administrator? Let me know and I'll check it out.

**Comment by sambernet** [comment]
If called directly (using 'update --standalone') it works seamlessly. 

We did dependency upgrades today and completely wiped out our node_modules folder. Looks like on this combination of npm/protractor the webdriver-manager.cmd gets installed in the ``node_modules/.bin`` folder by ``npm install``. It is *not* available anymore in the ``node_modules/protractor/bin`` folder!

To reproduce you probably need to wipe the node_modules folder if you are/were using an older version of npm or used the same workspace with protractor 2.5.1 before. Might even be reproducible on non-windows systems. Didn't try if downgrading npm also solves the problem, though (downgrading gulp-protractor and gulp does).

**Comment by ghpabs** [comment]
Same issue here - win7, node v4.2.2. I'm a new user so my `node_modules` was clean. Which is inline with what @sambernet said above.

**Comment by mattfritz** [comment]
Pretty sure [this PR](https://github.com/mllrsohn/gulp-protractor/pull/80) broke Windows implementation. The `webdriver-manager.cmd` file has always been in `node_modules/.bin` but this new version only looks in the `node_modules/protractor/bin` directory to avoid symlink issues.

I'll revert this PR for now and we can look for a different approach to the `npm install --no-bin-links` issue.

**Comment by mattfritz** [comment]
https://github.com/mllrsohn/gulp-protractor/pull/89 was reverted a moment ago, and released in `v2.1.0`.

@DatenMetzgerX @sambernet @ghpabs please give it a shot and let me know if that doesn't fix the issue, as I don't have access to a Windows machine.

**Comment by DatenMetzgerX** [comment]
Seems to work fine. Thanks a lot!

**Comment by ghpabs** [comment]
I'm still getting an error after updating to `v2.1.0`

```
Error: No selenium server jar found at the specified location (C:\project_x\node_modules\protractor\selenium\selenium-server-standalone-2.48.2.jar). Check that the version number is up to date.
```

Does selenium need to be installed separately?

**Comment by mattfritz** [comment]
That is a different error... it is indicating that the selenium jar did not get downloaded. Did you run the `webdriver_update` task? You can add the selenium updater task to your gulpfile:

```js
var webdriver_standalone = require("gulp-protractor").webdriver_standalone;
gulp.task('webdriver_standalone', webdriver_standalone);
```

**Comment by ghpabs** [comment]
Thanks for the speedy response.

When running the task above I get the following message:
```
Selenium Standalone is not present. Install with webdriver-manager update --standalone
```

However, when I run `webdriver-manager update --standalone` I get:
```
λ  webdriver-manager update --standalone
selenium standalone is up to date.
chromedriver is up to date.
```

**Comment by ghpabs** [comment]
I understand I need to update/generate the jar inside the protractor folder. I think I can take it from here. Thanks!

**Comment by Shyam-Chen** [comment]
I have the same problem.

```bash
> Vanilla-Starter-Kit@1.0.0 webdriver /home/travis/build/Shyam-Chen/Vanilla-Starter-Kit
> gulp webdriver
[06:01:26] Using gulpfile ~/build/Shyam-Chen/Vanilla-Starter-Kit/gulpfile.js
[06:01:26] Starting 'webdriver'...
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/travis/build/Shyam-Chen/Vanilla-Starter-Kit/node_modules/.bin/webdriver-manager ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
